-- Run this in Supabase SQL editor to fix the Message Board schema.

alter table public.messages
  add column if not exists author text;

alter table public.messages
  add column if not exists message text;

alter table public.messages
  add column if not exists created_at timestamptz not null default now();

-- Optional: if your table does not exist yet, use this instead of the ALTERs above.
-- create table if not exists public.messages (
--   id bigint generated by default as identity primary key,
--   author text not null,
--   message text not null,
--   created_at timestamptz not null default now()
-- );

-- Optional RLS policies if needed:
-- alter table public.messages enable row level security;
-- create policy "Allow read messages" on public.messages for select using (true);
-- create policy "Allow insert messages" on public.messages for insert with check (true);